.TH MFPX "1" "February 2020" "mfpx 1.2" "User Commands"
.SH NAME
mfpx \- mfpx
.SH SYNOPSIS
.B mfpx
[\fI\,COMMAND\/\fR]
.SH DESCRIPTION
Extracts, and processes ELO rating lists.
Currently the portuguese chess federation.
.HP
Options:
.HP
\fB\-h\fR,\-\-help   \fB\-\-\fR display help and exit
.HP
\fB\-\-version\fR   \fB\-\-\fR display version and exit
.HP
\fB\-i\fR          \fB\-\-\fR Open database iteractively
.HP
\fB\-u\fR          \fB\-\-\fR Update lists
.HP
\fB\-p\fR          \fB\-\-\fR Print relevants environment variables
.HP
\fB\-l\fR          \fB\-\-\fR List installed scripts
.HP
\fB\-r\fR [SCRIPT] \fB\-\-\fR Run installed scripts
.HP
\fB\-c\fR [SCRIPT] \fB\-\-\fR Run custom script
.SH EXAMPLES
.TP
mfpx \-u \-\- updates database
.SH AUTHOR
Written by Carlos A. Pinto Machado
.SH "REPORTING BUGS"
Report bugs to <cpmachado@protonmail.com>
or file a issue at https://github.com/cpmachado/bin
.SH COPYRIGHT
Copyright \(co 2020 Carlos Pinto Machado
